version: 2.1

orbs:
  node: circleci/node@5.1.0
jobs:
  test:
    parameters:
      version: 
        default: "stable"
        description: Node.JS version to install
        type: string
    docker:
      - image: cimg/node:<<parameters.version>>
    steps:
      - checkout
      - node/install-packages
      - run: npm run test
      - run:
          name: "Test that build is successful"
          command: npm run build
      - run:
          name: "Test that compile is successful"
          command: npm run compile
  deploy:
    docker:
      - image: cimg/node:current
    steps:
      - checkout
      - node/install-packages
      - run: npx semantic-release
workflows:
  test:
    jobs:
      - test:
          matrix:
            parameters:
              version:
                - "current"
                - "lts"
      - deploy:
          requires:
            - test